__all__ = [	"checkIfShieldFlowCase",
			"Q2Vel",
			"createName",
			"getParametersFromCase",
			"findShieldCases",
			"cleanCorruptCases",
			"paramsToGenesettings",
			"paramsListToGenesettings",
			"getShieldCaseResults",
			]
